travis:
  secure:
    BINSTAR_TOKEN: wyxiSrfKjPa1ylHglHag6qGik94xcVvbTRYVYo5SoB/U8tIKwo3emtHDL+yZIn06hRsdoFZ7A6J+Cu5i3Pkr0rrnF6Wtkez9F36XPvVZHuXnSbdCek70RleRRIDniDJaFQNKnDv62xhU/qTxiLFEpscNrBX7kGfTHsdByui+BUVA/bAJeKBAlmmeb/IijG7sWUFjcDtz9S/+eWSg/A4ea0biUNS/9x1AFDFINuw3RMAyReram2QSchzMtqD7Jscm5Qe7so0e0buN3gxhcMvSG1bj3v/rfR8JnFRXqTvnlSBeMaRGctFzULdTu3maPWvexMqjOuPDCoh8iXDsucYRsDVlL0xQSnXlaAotD13thjdgkW1sjvu9vwDBPPaScCTPy/xN6v2NgWF6MuCOaNbCTkzxboG3fnJ6ZAJo05SAunPpoNWSiIbvbfrOyqGwLxRVwJCpQf/eXUqriG0eNqomwv3Q+wtF7nuRKxs5emMyZtrckvQCciNq9gOC5m8PPRoS0npaESjzb/8mSndoTDybsFd9gbYPBazazELM2JGE1R/8Xxdkm89KeWV1CFjl7lnl2Fo7tUJjMS9ffJkM4xRzpDRmjvt6JdvLiMBbvRjHwuFWmVGlP+LwhsX5ZCgTOBjKs6PTW6ybkNggtvAMYHZw1wz6zvY9z04OeYc03DxlftQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
